#!/bin/sh
set -e

# Run laravel artisan commands
usermod -a -G www-data root
php /var/www/html/artisan config:clear
php /var/www/html/artisan cache:clear
php /var/www/html/artisan view:clear
php /var/www/html/artisan route:clear

php /var/www/html/artisan migrate --force

# Run laravel queue commands

#php /var/www/html/artisan queue:work --timeout=300
#php /var/www/html/artisan queue:restart
#php /var/www/html/artisan queue:retry all

php /var/www/html/artisan schedule:work &

# Start app services
service nginx restart
/usr/bin/supervisord -n -c /etc/supervisord.conf &
php-fpm
