version: '3'

services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./back:/var/www/backend

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./front:/var/www/frontend
