version: '3'
services:
  backend:
    build: ./back
    container_name: backend
    restart: always
    ports:
      - "8000:8000"
    networks:
      - app_network
      
  frontend:
    build: ./front
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge