version: '3.7'

services:

  #back
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    volumes:
      - ./back:/var/www
    expose:
      - "9000"
    networks:
      - app_network

  db:
    image: mysql:5.7.22
    restart: unless-stopped
    environment:
        MYSQL_DATABASE: ${DB_DATABASE:-laravel}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
        MYSQL_PASSWORD: ${DB_PASSWORD:-userpass}
        MYSQL_USER: ${DB_USERNAME:-username}
    volumes:
      - ./back/.docker/mysql/dbdata:/var/lib/mysql
    ports:
      - "3388:3306"
    networks:
      - app_network

  redis:
    image: redis:latest
    networks:
      - app_network

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front:/app
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge